---

name: tests

on: push

jobs:

  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Dependencies
        run: make install

      - name: Generate Key
        run: php artisan key:generate

      - name: Run Tests
        run: make test
